# Generated by Django 3.2.7 on 2021-09-13 12:21

import art_artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('paintistname', models.CharField(max_length=40, null=True, verbose_name='هنرمند')),
                ('subject', models.CharField(max_length=40, verbose_name='موضوع')),
                ('about', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateField(verbose_name='تاریخ ایجاد')),
                ('material', models.CharField(max_length=40, verbose_name='متریال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=art_artist.models.upload_image_path, verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'هنر',
                'verbose_name_plural': 'هنرها',
            },
        ),
    ]
