# Generated by Django 3.2.7 on 2021-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='availabale',
            field=models.BooleanField(default=True, verbose_name='دردسترس / دردسترس نیست'),
        ),
    ]
