# Generated by Django 3.2.7 on 2021-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_artist', '0002_art_availabale'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='شناسه کاربر سانده'),
        ),
    ]
