# Generated by Django 3.2.7 on 2021-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_artist', '0003_art_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='شناسه کاربر سازده'),
        ),
    ]
