# Generated by Django 3.2.7 on 2021-09-13 12:55

from django.db import migrations, models
import wall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=40, verbose_name='صاحب')),
                ('location', models.TextField(verbose_name='مکان')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('space_count', models.IntegerField(null=True, verbose_name='فضای خالی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=wall.models.upload_image_path, verbose_name='تصویر')),
                ('price', models.IntegerField(default=0, verbose_name='هزینه اجاره')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'دیوار',
                'verbose_name_plural': 'دیوارها',
            },
        ),
    ]
