# Generated by Django 3.2.7 on 2021-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_wall_availabale'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='شناسه کاربر سازنده'),
        ),
    ]
