# Generated by Django 3.2.7 on 2022-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_wall_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='availabale',
            field=models.BooleanField(default=True, verbose_name='اجاره شده'),
        ),
    ]
