# Generated by Django 3.2.7 on 2021-09-15 08:53

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True, verbose_name='نام')),
                ('subject', models.CharField(max_length=40, null=True, verbose_name='موضوع')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(null=True, verbose_name='تاریخ پایان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=reservation.models.upload_image_path, verbose_name='تصویر')),
                ('about', models.TextField(null=True, verbose_name='درباره')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('price', models.IntegerField(default=0, verbose_name='هزینه رزرو')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزوها',
            },
        ),
    ]
