# Generated by Django 3.2.7 on 2021-10-21 15:53

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20211009_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=reservation.models.upload_qrcode_image_path, verbose_name='کداسکن'),
        ),
    ]
