# Generated by Django 3.2.7 on 2022-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reserv_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='شناسه کاربر سازده'),
        ),
    ]
