# Generated by Django 3.2.7 on 2022-01-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reserv_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='creator_id',
            field=models.IntegerField(verbose_name='شناسه کاربر سازده'),
        ),
    ]
